version: 3.0
services:
  organizer:
    build:
      dockerfile: /src/main/docker/Dockerfile.jvm
      context: .
    restart: on-failure
    depends_on:
      - mongo
      - emqx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizer.rule=Host(`organizer.stock.up`)"
      - "traefik.http.routers.organizer.entrypoints=web"
      - "traefik.http.services.grafana.organizer.server.port=8082"
    ports:
      - "8082:80"
    networks:
      organizer:
        - ipv4_address: 172.16.0.10
  mongo:
    image: mongo:4.4.1
    restart: on-failure
    volumes:
      - dbdata:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      organizer:
        - ipv4_address: 172.16.0.11
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`mongodb.stock.up`)"
      - "traefik.http.routers.mongo-express.entrypoints=web"
      - "traefik.http.services.mongo-express.server.port=8081"
    networks:
      organizer:
        - ipv4_address: 172.16.0.12
  traefik:
    image: "traefik:v2.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      organizer:
        - ipv4_address: 172.16.0.1
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_HTTP_ADDR: "192.168.1.10"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.stock.up`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - grafana_logs/:/var/log/grafana
      - grafana_data/:/var/lib/grafana
      - grafana_home/:/usr/share/granana
    networks:
      organizer:
        - ipv4_address: 172.16.0.13
  prometheus:
    image: prom/prometheus:v2.21.0
    restart: always
    ports:
      - "9000:9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.stock.up`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9000"
    volumes:
      - prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      organizer:
        - ipv4_address: 172.16.0.14
  emqx:
    image: emqx/emqx:v4.0.0
    restart: always
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
    volumes:
      - emqx_data/:/opt/emqx/data
      - emqx_data/etc/:/opt/emqx/etc
      - emqx_data/logs/:/opt/emqx/log
    networks:
      organizer:
        - ipv4_address: 172.16.0.2
      emqx-bridge:
        aliases:
          - node1.emqx.io
volumes:
  dbdata:
  grafana_logs:
  grafana_data:
  grafana_home:
  prometheus:
  prometheus-data:
  emqx_data:
networks:
  emqx-bridge:
    driver: bridge
  organizer:
    driver: bridge